// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type BillingAddressInput struct {
	BillingName          string `json:"billingName"`
	BillingPhone         string `json:"billingPhone"`
	BillingAddress       string `json:"billingAddress"`
	BillingPostalCode    string `json:"billingPostalCode"`
	BillingSubDistrictID int    `json:"billingSubDistrictId"`
}

type City struct {
	ID         string    `json:"id"`
	Name       *string   `json:"name"`
	Lat        *string   `json:"lat"`
	Lon        *string   `json:"lon"`
	ProvinceID *int      `json:"provinceId"`
	Province   *Province `json:"province"`
}

type CityInput struct {
	ProvinceID int `json:"provinceId"`
}

type Country struct {
	ID   string  `json:"id"`
	Name *string `json:"name"`
	Lat  *string `json:"lat"`
	Lon  *string `json:"lon"`
	Code *string `json:"code"`
}

type CreateCustomerInput struct {
	FirstName       string                `json:"firstName"`
	LastName        string                `json:"lastName"`
	CompanyName     string                `json:"companyName"`
	Email           string                `json:"email"`
	Phone           string                `json:"phone"`
	BillingAddress  *BillingAddressInput  `json:"billingAddress"`
	ShippingAddress *ShippingAddressInput `json:"shippingAddress"`
}

type CreateCustomerPayload struct {
	Customer *Customer `json:"customer"`
}

type Customer struct {
	ID              string           `json:"id"`
	FirstName       string           `json:"firstName"`
	LastName        string           `json:"lastName"`
	CompanyName     string           `json:"companyName"`
	Email           string           `json:"email"`
	Phone           string           `json:"phone"`
	ProfileID       int              `json:"profileId"`
	CustomerAddress *CustomerAddress `json:"customerAddress"`
}

type CustomerAddress struct {
	ID                 string `json:"id"`
	CustomerID         int    `json:"customerId"`
	Name               string `json:"name"`
	Phone              string `json:"phone"`
	Address            string `gorm:"column:address_1" json:"address"`
	PostalCode         string `json:"postalCode"`
	Country            string `json:"country"`
	Province           string `json:"province"`
	City               string `json:"city"`
	District           string `json:"district"`
	SubDistrict        string `json:"subDistrict"`
	BillingName        string `json:"billingName"`
	BillingPhone       string `json:"billingPhone"`
	BillingAddress     string `json:"billingAddress"`
	BillingPostalCode  string `json:"billingPostalCode"`
	BillingCountry     string `json:"billingCountry"`
	BillingProvince    string `json:"billingProvince"`
	BillingCity        string `json:"billingCity"`
	BillingDistrict    string `json:"billingDistrict"`
	BillingSubDistrict string `json:"billingSubDistrict"`
}

type District struct {
	ID     string  `json:"id"`
	Name   string  `json:"name"`
	Lat    *string `json:"lat"`
	Lon    *string `json:"lon"`
	CityID *int    `json:"cityId"`
	City   *City   `json:"city"`
}

type DistrictInput struct {
	CityID int `json:"cityId"`
}

type Province struct {
	ID        string   `json:"id"`
	Name      *string  `json:"name"`
	Lat       *string  `json:"lat"`
	Lon       *string  `json:"lon"`
	CountryID *int     `json:"countryId"`
	Country   *Country `json:"country"`
}

type ProvinceInput struct {
	CountryID int `json:"countryId"`
}

type ShippingAddressInput struct {
	Name          string `json:"name"`
	Phone         string `json:"phone"`
	Address       string `json:"address"`
	PostalCode    string `json:"postalCode"`
	SubDistrictID int    `json:"subDistrictId"`
}

type SubDistrict struct {
	ID         string    `json:"id"`
	Name       *string   `json:"name"`
	Lat        *string   `json:"lat"`
	Lon        *string   `json:"lon"`
	PostalCode *string   `json:"postalCode"`
	DistrictID *int      `json:"districtId"`
	District   *District `json:"district"`
}

type SubDistrictInput struct {
	DistrictID int `json:"districtId"`
}
